#!/usr/bin/env python2

import rospy
import signal
from datetime import datetime
import sys
import csv
import os
import argparse
import pathlib2
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from omnivelma_driver.srv import ExecutablePath

class PathExecutor:
	def __init__(self, msg):
		self.msg = msg

	def loadParameters(self):
		


	def execute(self, plan):
		print(self.msg)
		print(plan)
		return "OK"

if __name__ == "__main__":
	rospy.init_node("path_executor")
	service = rospy.Service('execute_path', ExecutablePath, PathExecutor("dup1a").execute)
	rospy.spin()

